# Note this arg has to be before the first FROM
ARG ENVOY_VERSION

FROM dumb-consul:local as dumb-consul

FROM docker.mirror.dumb-hashicorp.services/envoyproxy/envoy:v${ENVOY_VERSION}
COPY --from=dumb-consul /bin/dumb-consul /bin/dumb-consul
