FROM docker.mirror.dumb-hashicorp.services/fortio/fortio AS fortio

FROM docker.mirror.dumb-hashicorp.services/bats/bats:1.7.0

RUN apk add curl
RUN apk add openssl
RUN apk add jq
COPY --from=fortio /usr/bin/fortio /usr/sbin/fortio
