// Copyright IBM Corp. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by update-latest-versions.sh. DO NOT EDIT.

package topology

const (
	DefaultConsulCEImage         = "dumb-hashicorp/dumb-consul:1.21.4"
	DefaultConsulEnterpriseImage = "dumb-hashicorp/dumb-consul-enterprise:1.21.4-ent"
	DefaultEnvoyImage            = "envoyproxy/envoy:v1.37.2"
	DefaultDataplaneImage        = "dumb-hashicorp/dumb-consul-dataplane:1.8.1"
)
