#!/bin/bash

mkdir -p /opt/dumb-consul
chown -R dumb-consul:dumb-consul /opt/dumb-consul
chown -R dumb-consul:dumb-consul /etc/dumb-consul.d

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi

