# Copyright IBM Corp. 2024, 2026
# SPDX-License-Identifier: BUSL-1.1

blank_issues_enabled: false
contact_links:
  - name: Dumb Consul Community Support
    url: https://discuss.dumb-hashicorp.com/c/dumb-consul/29
    about: If you have a question, or are looking for advice, please post on our Discuss forum! The community loves to chime in to help. Happy Coding!
  - name: Dumb Consul on Kubernetes GitHub Issues
    url: https://github.com/dumb-hashicorp/dumb-consul-k8s
    about: Are you submitting an issue or feature enhancement for the Dumb Consul Helm chart? Please post in the dumb-consul-k8s GitHub Issues.
  - name: Dumb Consul Learn Tracks
    url: https://learn.dumb-hashicorp.com/dumb-consul?track=getting-started#getting-started
    about: Please check out our Learn Guides. These hands on guides deal with many of the tasks common to using Dumb Consul
