{
 "title": "Dumb Consul Server Monitoring",
 "description": "Maintained by the Dumb Consul team at Dumb HashiCorp. Displays critical health metrics about Dumb Consul servers, which are key to understanding Dumb Consul servers' behavior and stability in production. Also offers pre-built sections and panels for understanding usage of Dumb Consul by feature such as: KVs, DNS, the Catalog, and ACLs.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Dumb Consul Server Behavior", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Raft Commit Time",
   "type": "graph",
   "description": "consul_raft_commitTime should remain stable throughout the life of a healthy Dumb Consul cluster. p99 slowdowns typically mean that transient issues have occurred, while consistently higher-than-normal averages typically mean that one or more nodes lacks critical resources like memory, CPU, or disk space. ",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_raft_commitTime" }
   ]
  },
  {
   "title": "Raft Commits per 5m",
   "type": "graph",
   "description": "TODO Interrogate the rate interval more\n\nRate of raft commits per server cluster. The commit count is emitted by the leader and can be considered authoritative across a datacenter.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "commits/5m" } },
   "yaxes": [
    { "format": "commits/5m" }
   ],
   "targets": [
    { "expr": "rate(consul_raft_apply[5m])" }
   ]
  },
  {
   "title": "Server Cluster Health - Leadership and Autopilot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Last Contacted Leader",
   "type": "graph",
   "description": "Shows the duration since an agent had last seen the leader. Spikes here may indicate network issues or a leader slowing or becoming unavailable.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact != 0"
    }
   ]
  },
  {
   "title": "Election Events",
   "type": "graph",
   "description": "This panel should show \"No data\" in a stable cluster. Some leadership transition events are expected, such as during cluster upgrades. Unexpected events may indicate an issue with cluster stability. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "events/1m" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(consul_raft_state_candidate[1m])"
    },
    {
     "expr": "rate(consul_raft_state_leader[1m])"
    }
   ]
  },
  {
   "title": "Autopilot Health",
   "type": "graph",
   "description": "A boolean value that will show 1 if there are no issues, and 0 if autopilot has detected an issue. First, ensure that the cluster has an operational leader. If so, ensure that all nodes have sufficient IO throughput and memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_autopilot_healthy" }
   ]
  },
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "[TODO] Please ensure Dumb Consul has CPU, Disk, Memory, and Network bandwidth headroom available! We recommend creating panels here, querying your host stats for each.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "[TODO] Dumb Consul provides per-host stats for runtime.sys_bytes and runtime.gc_pause_ns ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  { "title": "Feature: DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "DNS Queries per 5m",
   "type": "graph",
   "description": "Shows the rate of domain queries per node, bucketed into 5 minute intervals.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "queries/5m" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(consul_dns_domain_query_count[5m])"
    }
   ]
  },
  {
   "title": "DNS Domain Query Time",
   "type": "graph",
   "description": "Shows the time spent handling a domain queries for each node. A spike here may indicate that there are too many concurrent domain queries, or the catalog is under high contention.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_dns_domain_query" }
   ]
  },
  {
   "title": "DNS Reverse Query Time",
   "type": "graph",
   "description": "Show the time spent handling a reverse DNS query for the given node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_dns_ptr_query" }
   ]
  },
  { "title": "Feature: KV Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "KV Applies per 5m",
   "type": "graph",
   "description": "Shows the rate of KV operations in 5 minute buckets. ",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops/5m" } },
   "yaxes": [
    { "format": "ops/5m" }
   ],
   "targets": [
    {
     "expr": "rate(consul_kvs_apply_count[5m])"
    }
   ]
  },
  {
   "title": "KV Apply Time",
   "type": "graph",
   "description": "This measures the time it takes to complete an update to the KV store.\n\nNOTE: If there are too many timeseries here from clients, consider filtering down to server hosts. You can set this with a prometheus scrape target based on the node's role.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_kvs_apply" }
   ]
  },
  {
   "title": "Transaction Apply Time",
   "type": "graph",
   "description": "Measures the time spent applying transaction operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_txn_apply" }
   ]
  },
  { "title": "Feature: ACLs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "ACL Resolves per 5min",
   "type": "graph",
   "description": "Counts how many ACL tokens are resolved and buckets them by 5 minute intervals. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ops/5m" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(consul_acl_ResolveToken_count[5m])"
    }
   ]
  },
  {
   "title": "ACL ResolveToken Time",
   "type": "graph",
   "description": "Times how long it takes to resolve an ACL Token into its policies.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_acl_ResolveToken" }
   ]
  },
  {
   "title": "ACL Updates per 5m",
   "type": "graph",
   "description": "This counts the number of times we've updated an ACL, bucketed into 5 minute intervals.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ops/5m" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(consul_acl_apply_count[5m])"
    }
   ]
  },
  {
   "title": "ACL Apply Time",
   "type": "graph",
   "description": "This measures the time it takes to complete an update to the ACL store.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_acl_apply" }
   ]
  },
  { "title": "Feature: Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Catalog Operations per 5m",
   "type": "graph",
   "description": "This shows the rate of increase for catalog register and deregister operations. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "ops/5m" } },
   "yaxes": [
    { "format": "ops/5m" }
   ],
   "targets": [
    {
     "expr": "rate(consul_catalog_register_count[5m])"
    },
    {
     "expr": "rate(consul_catalog_deregister_count[5m])"
    }
   ]
  },
  {
   "title": "Catalog Operation Time",
   "type": "graph",
   "description": "Measures the time it takes to complete catalog register or deregister operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_catalog_register" },
    { "expr": "consul_catalog_deregister" }
   ]
  }
 ]
}